# Generated by Django 5.0.3 on 2024-03-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Dish", new_name="Drink",),
    ]
