# Generated by Django 5.0.3 on 2024-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0002_rename_dish_drink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotdog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("cover", models.ImageField(upload_to="covers")),
            ],
        ),
    ]
