# Generated by Django 5.0.3 on 2024-03-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0003_hotdog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotdog",
            name="cover",
            field=models.ImageField(upload_to="hotdogs"),
        ),
        migrations.CreateModel(
            name="Spice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.ManyToManyField(to="app_cafe.hotdog")),
            ],
        ),
    ]
