# Generated by Django 5.0.3 on 2024-03-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0004_alter_hotdog_cover_spice"),
    ]

    operations = [
        migrations.DeleteModel(name="Spice",),
    ]
