# Generated by Django 5.0.3 on 2024-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0005_delete_spice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hotdog",
            name="Spices",
            field=models.ManyToManyField(to="app_cafe.spice"),
        ),
    ]
