# Generated by Django 5.0.3 on 2024-03-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0006_spice_hotdog_spices"),
    ]

    operations = [
        migrations.AddField(
            model_name="spice",
            name="cover",
            field=models.ImageField(default=0, upload_to="Spicecovers"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spice",
            name="level",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
