# Generated by Django 5.0.3 on 2024-03-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0007_spice_cover_spice_level"),
    ]

    operations = [
        migrations.RemoveField(model_name="hotdog", name="Spices",),
    ]
