# Generated by Django 5.0.3 on 2024-03-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0009_alter_spice_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotdog_Spice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotdog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_cafe.hotdog",
                    ),
                ),
                (
                    "spice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_cafe.spice"
                    ),
                ),
            ],
        ),
    ]
