# Generated by Django 5.0.3 on 2024-03-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0010_hotdog_spice"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotdog",
            name="data_create",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="hotdog",
            name="data_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
