# Generated by Django 5.0.3 on 2024-03-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0011_hotdog_data_create_hotdog_data_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotdog",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
