# Generated by Django 5.0.3 on 2024-03-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0012_drink_price_hotdog_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotdog",
            name="composition",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
