# Generated by Django 5.0.3 on 2024-03-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cafe", "0014_rename_spice_spicy_rename_spice_hotdog_spice_spicy"),
    ]

    operations = [
        migrations.RenameModel(old_name="Hotdog_Spice", new_name="Hotdog_Spicy",),
    ]
